name: Deploy stuff from main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env: 
  actions: Use this
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Simple SFTP
      uses: Atyn/simple-sftp-action@0.0.2
      with:
        url: sftp://${{ secrets.USER }}:${{ secrets.PASSWORD }}@ssh.strato.de:22/main
        localdir: /
