name: Deploy stuff from main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.1
      with:
        host: 'ssh.strato.de'
        port: 22
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        localPath: './'
        remotePath: './main/'
