name: Deploy stuff from sebastian
on:
  push:
    branches: [ dev-sebastian ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: e-assessment.bplaced.net 
        username: e-assessment_ftp
        password: nSgHRbL8b4eajGxd
        server-dir: "./www/sebastian/"
        log-level: verbose
