name: Deploy stuff from sebastian
on:
  push:
    branches: [ dev-sebastian ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: e-assessment.bplaced.net 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        localDir: "/"
        remoteDir: "/www/sebastian"
        options: "--delete --asci"
