name: Deploy stuff from yoanna
on:
  push:
    branches: [ dev-yoanna ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: e-assessment.bplaced.net 
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        server-dir: "./www/yoanna/"
